### PR TITLE
New agent

### PR DESCRIPTION
**Pull request by xiaohe27**
Basically, this PR is the same as the previous agent one.
But the commit history is cleaned by a rebase operation.
Some more test will be done before merging.

### CODE REVIEW

**Comment by xiaohe27** [comment]
@yzhang90 
I rebase on @seriousamlqz 's commits.
I did some tests, and in this PR the JavaMOP 's statistics option works well, given the rv-monitor is Philip's featureRemovalRefactor branch.
Basically, you need to compile the mop file with -s option.
A simple way of testing statistics feature is using current agent which will be removed later.
javamop -agent -s YourMOPFile.mop
It also works with javamopagent, but involving a little more steps, which I am going to refactor soon.

**Comment by yzhang90** [comment]
I see. I'm more than happy to test it after your refactoring.

Best,

Yi

**Comment by xiaohe27** [comment]
@seriousamlqz @yzhang90 @owolabileg @kheradmand 
Seems that I moved too far, maybe I should just focusing on removing the old agent related things in this PR. But in the previous commit, I deleted the part that invoking rv-monitor to generate monitor library, which is desired in the near future;

**Comment by seriousamlqz** [comment]
You can revert your commit.

**Comment by xiaohe27** [comment]
@seriousamlqz 
The problem is that I did too much removal in a single commit....
Thanks for this tip, but I've created a new pull request.
@yzhang90 In fact, in this branch, I've achieved the effect that the generated .aj file and .rvm file are separate and you do not need to remove the classes from .aj file manually in order to use javamopagent...

**Pull request closed without merging**
