### PR TITLE
Agent

### PR DESCRIPTION
**Pull request by xiaohe27**
I've removed the -baseaspect option in javamopagent, and only keep that option in javamop.
I've inlined the contents of the default BaseAspect.aj in the .aj file generated by javamop if there is no user defined BaseAspect is provided.
I also modify the name of the aspect generated by javamop in -merge option so that it is consistent with the library generated by rv-monitor.

I've passed the mvn verify, and maybe @seriousamlqz we  can discuss how to compare the contents of agent.jar generated by previous javamop's -agent option and the one generated by our separate javamopagent tool in order to increase our confidence.

### CODE REVIEW

**Comment by seriousamlqz** [comment]
Thanks He, I will take a look at your changes.

**Comment by seriousamlqz** [comment]
@xiaohe27 I madea some minor comments, overall it looks good to me.

**Comment by xiaohe27** [comment]
@seriousamlqz  I've compared the agent jars generated by -agent option and javamopagent, and I found that only the aspect classes are different. However, if I use Intellij to view the java code from these class files, their contents are exactly the same. In addition to this, I also notice that in my test case, both the BaseAspect.class and HasNextMonitorAspect.class (generated by javamopagent) are 26 bytes less than their counterparts generated by -agent option. I'll do more experiments to understand the reason.

**Comment by xiaohe27** [comment]
@seriousamlqz I've found the reason why the byte code of aspects differ in the agent.jars generated by javamop's -agent option and javamopagent. The directory from which we compile the .aj file can affect the generated byte code of the aspects. After using `-d` option in javamop and put the .aj file in exactly the same directory when I execute javamopagent, I made the contents of the two jars (unzip first) exactly the same (The binary jar files still differs though).

**Comment by seriousamlqz** [comment]
@xiaohe27 You can go ahead and remove the old agent generator, and make sure everything is OK (commandline option, document, etc). Then we can merge it.

**Comment by xiaohe27** [comment]
The latest newAgent PR contains all the stuff in this PR.

**Pull request closed without merging**
