### PR TITLE
Output

### PR DESCRIPTION
**Pull request by xiaohe27**
Make the output of JavaMOP in good shape.

From now on, JavaMOP takes a set of mop files/folders as input, and output .aj and .rvm files (separately).  RV-Monitor will not be invoked within JavaMOP and it will become users' job to invoke RV-Monitor so that monitoring library can be generated.

If the output directory is specified, then the output will be placed in the output directory; otherwise, they will be put aside the .mop file for each input .mop file.

### CODE REVIEW

**Comment by xiaohe27** [comment]
After discussing with @kheradmand and @seriousamlqz etc, we think the enforcement problem should be inside RV-Monitor, and not relevant to the code generated by JavaMOP. 
This is a major change to JavaMOP, @grosu  @seriousamlqz @kheradmand @yzhang90 @owolabileg @ylies
Any comments are welcomed.

**Comment by xiaohe27** [comment]
The enforcement problem was reported as the issue runtimeverification/rv-monitor#144 in rv-monitor's repository some time ago by Ali.

**Comment by grosu** [comment]
Yes, of course, the enforcement capability will be mostly in RV-Monitor!  It is the method called when the event is generated that blocks the thread, and not the instrumentation.

But JavaMOP will also need to parse the syntax related to enforcement and to generate the right RV-Monitor spec.

**Comment by ylies** [comment]
I don't know if it has been reported, but it seems that some clarification is needed regarding the enforced property. If a regular expression E is indicated as the enforced property, it is not this property which is enforced but rather Sigma^* \setminus bad(L(E)), where Sigma is the set of events appearing in the program and bad(L) is the set of bad prefixes of a language L.

For what I understood, the current enforcement framework works only for safety properties (where for a safety property P, Sigma^* \setminus L(P) = Sigma^* \setminus bad(L(P)).

Assuming that the above problem is fixed, there is an implicit assumption which is that for any thread, there is almost one action involved and that can be suspended.

I actually thought about this problem a few years ago, when trying to refine the set of enforceable properties, trying to come with a practical definition. I came up with a definition of enforceable properties "in practice" on DFA. But sadly, I never published that because of lacking of an underlying solid monitoring infrastructure.

**Comment by xiaohe27** [comment]
@grosu With regard to the syntax related to enforcement, JavaMOP is able to parse the mop files containing (but not limited to) keywords like "enforce", "@deadlock", "@fail", "@nonfail", and generated rvm specifications correctly. @seriousamlqz You said that you would provide more test cases for enforcement, right? I will ensure JavaMOP is able to parse all the mop spec related to enforcement.

**Comment by seriousamlqz** [comment]
Right, I think most tests would be in RV-MONITOR side since the JavaMOP
part is covered by other tests. However we will add some in JavaMOP to test
the whole process end to end.

**Comment by xiaohe27** [comment]
I've updated part of the usage.md to reflect the change of output of JavaMOP. As the users need to be more conscious about and actively use rv-monitor, it requires more transitions between different steps of our use cases, so that the rv-monitor's appearance will not be too odd. @owolabileg Can you do some proofreading on the modified docs in the last three commits?

**Pull request merged**
